"""add compatibility_queries table

Revision ID: 2ff3ff07be85
Revises: 439c917ea55b
Create Date: 2026-06-18 14:07:38.546475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff3ff07be85'
down_revision: Union[str, Sequence[str], None] = '439c917ea55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compatibility_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('match_percentage', sa.Float(), nullable=False),
    sa.Column('matched_skills', sa.String(), nullable=False),
    sa.Column('missing_skills', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compatibility_queries')
    # ### end Alembic commands ###
